<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hugo Cochereau &amp; Grégory Jaillet">
<meta name="keywords" content="Hugo Cochereau, Data Science, Economiste, Statistiques, Machine learning, Python, R, SQL, Git, GitHub, LinkedIn">
<meta name="description" content="Avec un master en économie spécialisé en Data Science, j’ai une solide expérience en analyse statistique, économétrie et apprentissage automatique. Je suis actuellement à la recherche d’une opportunité professionnelle pour mettre à profit mes compétences.">

<title> Richesse = Démocratie ? – Hugo Cochereau</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../imgs/hc.ico" rel="icon">
<script src="../../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-HBVTRTQK8N"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-HBVTRTQK8N', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"fr"
  });
});
</script> 
  
<link href="../../../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="../../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="../../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

<script src="../../../site_libs/datatables-binding-0.34.0/datatables.js"></script>

<script src="../../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="../../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

<link href="../../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

<script src="../../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

<link href="../../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

<script src="../../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>

<script src="../../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<script>

    window.addEventListener('load', function () {

        document.getElementById("cc-nb-title").innerHTML = "🍪 Oh là là, des cookies !";

        document.getElementById("cc-nb-text").innerHTML = "J'utilise des cookies pour analyser le trafic sur le site. Pas de panique, ils sont aussi inoffensifs que des biscuits faits maison et totalement optionnels.";

    });



    document.addEventListener("DOMContentLoaded", function () {

        const navbarTitle = document.querySelector(".navbar-title");

        const text = navbarTitle.textContent;

        navbarTitle.innerHTML = "";



        for (let char of text) {

            const span = document.createElement("span");

            span.textContent = char;

            navbarTitle.appendChild(span);

        }

    });

</script>





<!-- Google tag (gtag.js) -->

<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-HBVTRTQK8N"></script>

<script>

    window.dataLayer = window.dataLayer || [];

    function gtag() { dataLayer.push(arguments); }

    gtag('js', new Date());



    gtag('config', 'G-HBVTRTQK8N');

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../assets/styles.css">
<link rel="stylesheet" href="../../sections_css/style_projets.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../imgs/hc.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title"></span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Recherche"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Basculer la navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../accueil.html"> 
<span class="menu-text">Accueil</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../sections/parcours.html"> 
<span class="menu-text">Parcours</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../sections/competences.html"> 
<span class="menu-text">Compétences</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../sections/projets.html"> 
<span class="menu-text">Projets</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/hugocoche" title="" class="quarto-navigation-tool px-1" aria-label="" target="_blank"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/hugo-cochereau-175448207" title="" class="quarto-navigation-tool px-1" aria-label="" target="_blank"><i class="bi bi-linkedin"></i></a>
    <a href="mailto:hugo.p-cochereau@outlook.fr" title="" class="quarto-navigation-tool px-1" aria-label="" target="_blank"><i class="bi bi-envelope"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><i class="fa-solid fa-balance-scale" aria-label="balance-scale"></i> Richesse = Démocratie ?</h1>
                  <div>
        <div class="description">
          Étude de l’impact de la richesse d’un pays sur son niveau de démocratie à l’aide de données de panel. La seconde partie de ce projet aborde des questions théoriques sur les séries temporelles.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">Économétrie</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Auteur·rice</div>
      <div class="quarto-title-meta-contents">
               <p>Hugo Cochereau &amp; Grégory Jaillet </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Date de publication</div>
      <div class="quarto-title-meta-contents">
        <p class="date">11 janvier 2024</p>
      </div>
    </div>
    
      
    </div>
    

  <div>
    <div class="keywords">
      <div class="block-title">Mots clés</div>
      <p>Hugo Cochereau, Data Science, Economiste, Statistiques, Machine learning, Python, R, SQL, Git, GitHub, LinkedIn</p>
    </div>
  </div>
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sur cette page</h2>
   
  <ul>
  <li><a href="#exercice-1" id="toc-exercice-1" class="nav-link active" data-scroll-target="#exercice-1">Exercice 1</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4">Question 4</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5">Question 5</a></li>
  <li><a href="#question-6" id="toc-question-6" class="nav-link" data-scroll-target="#question-6">Question 6</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8</a></li>
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9</a></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10</a></li>
  <li><a href="#question-11" id="toc-question-11" class="nav-link" data-scroll-target="#question-11">Question 11</a></li>
  <li><a href="#question-12" id="toc-question-12" class="nav-link" data-scroll-target="#question-12">Question 12</a></li>
  <li><a href="#question-13" id="toc-question-13" class="nav-link" data-scroll-target="#question-13">Question 13</a></li>
  </ul></li>
  <li><a href="#exercice-2" id="toc-exercice-2" class="nav-link" data-scroll-target="#exercice-2">Exercice 2</a>
  <ul class="collapse">
  <li><a href="#question-1-1" id="toc-question-1-1" class="nav-link" data-scroll-target="#question-1-1">Question 1</a></li>
  <li><a href="#question-2-1" id="toc-question-2-1" class="nav-link" data-scroll-target="#question-2-1">Question 2</a></li>
  <li><a href="#question-3-1" id="toc-question-3-1" class="nav-link" data-scroll-target="#question-3-1">Question 3</a></li>
  <li><a href="#question-4-1" id="toc-question-4-1" class="nav-link" data-scroll-target="#question-4-1">Question 4</a></li>
  <li><a href="#question-5-1" id="toc-question-5-1" class="nav-link" data-scroll-target="#question-5-1">Question 5</a></li>
  <li><a href="#question-6-1" id="toc-question-6-1" class="nav-link" data-scroll-target="#question-6-1">Question 6</a></li>
  <li><a href="#question-7-1" id="toc-question-7-1" class="nav-link" data-scroll-target="#question-7-1">Question 7</a></li>
  <li><a href="#question-8-1" id="toc-question-8-1" class="nav-link" data-scroll-target="#question-8-1">Question 8</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="exercice-1" class="level1 unnumbered">
<h1 class="unnumbered">Exercice 1</h1>
<section id="question-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-1">Question 1</h2>
<p>Il peut être intéressant d’analyser l’impact du niveau de richesse d’un pays (en utilisant le PIB par habitant comme indicateur) sur son degré de démocratie pour déterminer si les pays avec un haut niveau de richesse de ses habitants sont des modèles de démocratie ou bien si les pays pauvres sont inévitablement des dictatures. Ainsi, ce type d’étude peut permettre de valider les idées reçus ou bien de démontrer des réalités plus complexes.</p>
<p>Ensuite, on doit noter que la possession de données de panel est idéale pour étudier une durabilité de ce lien dans le temps. Cependant, les résultats de l’étude pourraient bien aboutir à une corrélation nulle entre ces deux facteurs car il faut prendre en compte le fait qu’énormément de facteurs rentrent en compte lorsque l’on discute du développement démocratique d’un pays, parmi cela, on pourrait évoquer des facteurs culturels ou encore la possible influence d’acteurs externes aux pays étudiés.</p>
<p>Enfin, si les résultats d’une telle étude étaient convaincants, qu’ils pouvaient démontrer une réelle corrélation entre les deux variables et non une simple causalité, alors cela permettrait à l’humanité de faire un grand pas dans la résolution des problèmes liés à la misère dans le monde.</p>
</section>
<section id="question-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-2">Question 2</h2>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-3f66c53e911885f9a22e" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-3f66c53e911885f9a22e">{"x":{"filter":"none","vertical":false,"data":[["Unique","Valeurs manquantes","Moyenne","Écart type","Minimum","Q1","Médiane","Q3","Maximum"],[11,0,1975,15.81,1950,1960,1975,1990,2000],[792,1503,4.32,2.85,0.04,1.92,3.86,6.51,12.18],[94,804,0.51,0.36,0,0.17,0.5,0.83,1],[528,1782,0.37,0.13,0.08,0.26,0.36,0.47,0.74],[245,396,22.47,6.33,14.4,17.7,19.6,27,41.3],[1239,1083,0.16,0.14,-0.77,0.1,0.18,0.24,0.74],[1602,660,26803.31,95292.10000000001,32,1627,5172,15820,1262456.12],[1232,1090,8.15,1.03,5.77,7.29,8.140000000000001,8.94,10.69]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>year<\/th>\n      <th>education<\/th>\n      <th>fhpolrigaug<\/th>\n      <th>laborshare<\/th>\n      <th>medage<\/th>\n      <th>nsave<\/th>\n      <th>population<\/th>\n      <th>lrgdpch<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5,6,7,8]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"year","targets":1},{"name":"education","targets":2},{"name":"fhpolrigaug","targets":3},{"name":"laborshare","targets":4},{"name":"medage","targets":5},{"name":"nsave","targets":6},{"name":"population","targets":7},{"name":"lrgdpch","targets":8}],"order":[],"autoWidth":false,"orderClasses":false,"rowCallback":"function(row, data, displayNum, displayIndex, dataIndex) {\nvar value=data[0]; $(this.api().cell(row, 0).node()).css({'color':'black','background-color':'grey'});\n}"}},"evals":["options.rowCallback"],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="question-3" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-3">Question 3</h2>
<p><span class="math display">\[fhpolrigaug_{it} = \beta_0 + \beta_1 lrgdpch_{it} + \varepsilon_{it}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(fhpolrigaug<span class="sc">~</span>lrgdpch,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> Data</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>        )</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table style="text-align:center">
<caption>
<strong>Modèle Q3</strong>
</caption>
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
fhpolrigaug
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.218<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.008)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-1.211<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.066)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
1,125
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.402
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.402
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.274 (df = 1123)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
755.300<sup>***</sup> (df = 1; 1123)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>On remarque que le coefficient associé à la variable <code>lrgdpch</code> est significativement différent de 0, donc le PIB par tête semble bien avoir un impact sur le niveau de démocratie d’un pays, ainsi, ce premier modèle nous indique qu’une augmentation de 1% du PIB par tete contribue a une hausse d’environ <strong>0.0022</strong> unités du niveau de démocratie.</p>
<p>Il ne faut cependant pas oublier que nous avons omis plusieurs facteurs en estimant ce modèle donc cette estimation de l’impact du PIB par tête sur le niveau de démocratie a de grandes chances d’être biaisée.</p>
</section>
<section id="question-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-4">Question 4</h2>
<p><span class="math display">\[fhpolrigaug_{it} = \beta_0 + \beta_1 lrgdpch_{it} + \beta_2 medage_{it} + \beta_3 education_{it} + \\ \beta_4 population_{it} + \beta_5 nsave_{it}
+ \beta_6 laborshare_{it} + \varepsilon_{it}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(fhpolrigaug<span class="sc">~</span>lrgdpch<span class="sc">+</span>medage<span class="sc">+</span>education<span class="sc">+</span>population<span class="sc">+</span>nsave<span class="sc">+</span>laborshare,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> Data</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        )</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table style="text-align:center">
<caption>
<strong>Modèle Q4</strong>
</caption>
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
fhpolrigaug
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.114<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.030)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medage
</td>
<td>
0.001
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
education
</td>
<td>
0.034<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.009)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
population
</td>
<td>
0.00000<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
nsave
</td>
<td>
-0.003
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.133)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
laborshare
</td>
<td>
0.323<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.109)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-0.647<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.198)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
432
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.422
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.414
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.262 (df = 425)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
51.725<sup>***</sup> (df = 6; 425)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>Ce modèle est sur données en coupe avec un nombre d’observations égal au nombre de pays présents dans la base de données multiplié par le nombre de périodes d’observations (tout en retirant les observation dont les données sont manquantes), de plus, les coefficients <span class="math inline">\(\beta\)</span> sont les mêmes pour toutes les unités individuelles, il n’y a donc pas de variation des coefficients en fonction de l’unité observé, on peut donc affirmer que c’est un <strong>modèle poolé</strong>.</p>
<p>On remarque que l’effet du logarithme de PIB par tete à était divisé par deux par rapport au modèle précédent, avec un coefficient de <strong>0.1135219</strong>.</p>
<p>De plus on remarque que <code>population</code> a un coefficient très proche de <strong>0</strong>, il y aurait donc une absence de liaison entre la variable population et la variable <code>fhpolrigaug</code> que l’on cherche a expliquer, en effecutant le test de corrélation de Spearman nous obtenons un coefficient de <strong>-0.071</strong> donc quasiemment proche de 0 , ce qui indique une indépendance et donc que la taille de la population n’a aucun effet sur le niveau de démocratie d’un pays.</p>
<p>On remarque de plus que la variable <code>éducation</code> a un impact plutôt significatif sur le modèle, on traduit donc qu’une augmentation d’une année d’éducation de la population âgée de plus de 25 ans entraine une hausse de <strong>0.034</strong> unité du degrés de démocratie.</p>
<p>Ensuite, on remarque que <code>laborshare</code> a un impact significatif dans ce modèle , avec un coefficient de <strong>0.323</strong>, cela traduit donc qu’une augmentation de 1 point de pourcentage de la part du travail dans la valeur ajoutée provoque une hausse de <strong>0.323</strong> unité de degré de démocratie.</p>
<p>Enfin on notera que selon ce modèle, le taux d’épargne ainsi que l’âge médian de la population n’aurait aucun impact significatif sur le degré de démocratie.</p>
</section>
<section id="question-5" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-5">Question 5</h2>
<p>Ce modèle est estimé sur beaucoup moins d’observations que lors de la question 3 car il inclue d’autres variables dont la valeur est inconnue pour un certain nombre d’observations, afin d’estimer les coefficients du modèle, ces observations ne sont donc pas utilisées ce qui réduit in fine le nombre d’observations utilisées pour construire ce nouveau modèle.</p>
<p>Peut-être que l’inclusion de ces observations n’auraient pas changé les implications de nos résultats, cependant, ceux-ci se retrouvent inévitablement biaisés car l’exclusion de ces différentes observations impliquent la présence d’un biais de sélection et peut-être d’un biais de non-réponse dû à une des caractéristiques du pays observé. Ainsi, ces deux biais influeront sur l’estimation des paramètres et des erreurs-types et donc sur la fiabilité du modèle.</p>
<p>En effet, si les données manquantes pouvaient apporter des informations très importante, le fait de ne pas pouvoir les inclure dans le modèle pourrait introduire de faux signaux dans nos analyses. Il faudra donc veiller à émettre des conclusions tenant compte de ces éventuels problèmes lorsque l’on interprétera ce modèle.</p>
</section>
<section id="question-6" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-6">Question 6</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Fixed_temps<span class="ot">&lt;-</span><span class="fu">lm</span>(fhpolrigaug<span class="sc">~</span>lrgdpch<span class="sc">+</span>medage<span class="sc">+</span>education<span class="sc">+</span>population<span class="sc">+</span>nsave<span class="sc">+</span>laborshare<span class="sc">+</span><span class="fu">factor</span>(year)<span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data=</span>Data[<span class="fu">which</span>(<span class="sc">!</span><span class="fu">is.na</span>(Data<span class="sc">$</span>year)),]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                )</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table style="text-align:center">
<caption>
<strong>Modele poolé avec indicatrice temporelles (1), Modèle poolé sans indicatrice temporelle (2)</strong>
</caption>
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
fhpolrigaug
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.145<sup>***</sup>
</td>
<td>
0.114<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.029)
</td>
<td>
(0.030)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medage
</td>
<td>
-0.003
</td>
<td>
0.001
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.003)
</td>
<td>
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
education
</td>
<td>
0.037<sup>***</sup>
</td>
<td>
0.034<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.009)
</td>
<td>
(0.009)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
population
</td>
<td>
0.00000<sup>***</sup>
</td>
<td>
0.00000<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00000)
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
nsave
</td>
<td>
-0.027
</td>
<td>
-0.003
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.126)
</td>
<td>
(0.133)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
laborshare
</td>
<td>
0.296<sup>***</sup>
</td>
<td>
0.323<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.104)
</td>
<td>
(0.109)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1960
</td>
<td>
-0.631<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.188)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1965
</td>
<td>
-0.681<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.190)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1970
</td>
<td>
-0.861<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.191)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1975
</td>
<td>
-0.904<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.192)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1980
</td>
<td>
-0.884<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.192)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1985
</td>
<td>
-0.826<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.192)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1990
</td>
<td>
-0.868<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.193)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
</td>
<td>
-0.647<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.198)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
432
</td>
<td>
432
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.887
</td>
<td>
0.422
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.883
</td>
<td>
0.414
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.247 (df = 419)
</td>
<td>
0.262 (df = 425)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
252.734<sup>***</sup> (df = 13; 419)
</td>
<td>
51.725<sup>***</sup> (df = 6; 425)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>En ajoutant des effets fixes temporels, le modèle prend en compte les variations annuelles spécifiques, ce qui peut améliorer la précision des estimations en éliminant une partie de la variance due à des facteurs temporels non observés. Cela peut rendre les résultats plus fiables et permet une meilleure interprétation des effets des variables explicatives sur la variable dépendante.</p>
<p>L’interprétation des coefficients des variables explicatives reste similaire, mais les effets fixes temporels permettent de contrôler les variations annuelles non observées. On pourrait interpréter les coefficients comme les effets moyens des variables explicatives sur la variable dépendante, en tenant compte des variations spécifiques à chaque année.</p>
<p>En somme l’ajout d’effets fixes temporels permet de capter tout choc eventuelles, liées a une année particuliére , par exemple la présence d’une guerre dans certains pays ou tout évènement suffisament important pouvant influencer significativement la vie d’un ou plusieurs pays.</p>
<p>Concernant l’interpretation :</p>
<ul>
<li><p>Pour la variable <code>lrgdpch</code> on remarque une hausse de son coeffficient par rapport au cas sans effets fixes temporels, avec un coefficient de <strong>0.145</strong> ;</p></li>
<li><p>De meme <code>éducation</code> voit aussi son coefficient augmenter, en passant de <strong>0.034</strong> à <strong>0.037</strong> ;</p></li>
<li><p>Cependant l’impact de la variable <code>laborshare</code> sur le degré de démocratie diminue , ce qui veut dire que sans les effets fixes temporels, le modèle sur-estimait l’impact de la part de travail dans la valeur ajouté sur le niveau de démocratie d’un pays ;</p></li>
<li><p>Il faut aussi noter que l’introduction d’effets fixes temporels indiquent un degré de démocratie moyen très différent en fonction de la période de temps étudiée. Par exemple, à autres facteurs fixés, on peut relever que le niveau de démocratie moyen dans les années 90 est en moyenne inférieur au niveau de démocratie moyen dans les années 60 de <strong>0.237</strong> unité. Il est aussi intéressant de constater que selon ce modèle, le degré de démocratie était en moyenne en plus élevé dans les années 60 (à autres facteurs fixés).</p></li>
</ul>
<p>Ces quelques remarques sont très intéressantes pour l’étude car la prise en compte de la temporalité de nos données impliquent des résultats différents. D’ailleurs on pourra aussi noter que la qualité d’ajustement de ce dernier modèle est plus élevé.</p>
</section>
<section id="question-7" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-7">Question 7</h2>
<p>La non-correction des erreurs-types dans les OLS sur le modèle poolé causerait différents problèmes dans notre modèle.</p>
<p>Tout d’abord, cela signifierait que l’on ne prendrait pas en compte l’autocorrélation des erreurs ou sérialité. En effet, Les données de panel présentent souvent une corrélation entre les observations successives pour la même unité au fil du temps. Or, si cette autocorrélation n’est pas prise en compte, les erreurs-types standard non corrigées peuvent sous-estimer l’incertitude entourant les coefficients estimés.</p>
<p>De plus, cela nous amèneraient à ne pas prendre en compte l’eventuelle hétéroscédasticité du modèle, et donc à utiliser des estimateurs qui ne seraient pas BLUE, ce qui implique aussi que les tests de significativé de ces coefficients nous conduiraient à très souvent rejeter l’hypothèse de nullité des coefficients dû à la sous-estimation des erreurs-types. Cette dernière information est cruciale car cela signifierait que ne pas corriger les erreurs-types pourraient nous amener à identifier un impact significatif d’une des variables explicative sur le niveau de démocratie alors que cet impact pourrait être nul.</p>
<p>Enfin, il ne faut pas oublier une éventuelle corrélation entre les observations des différents pays. Donc si cette corrélation n’est pas correctement prise en compte, les erreurs-types standard peuvent être biaisées.</p>
<p>En résumé Il est nécessaire de corriger les erreurs-types dans les OLS sur le modèle poolé afin de prévenir toute hétéroscédasticité pouvant biaiser les résultats. De plus, la nature temporelle des données de panel impose le risque de dépendance d’une variable à sa valeur passée, qui engendre aussi un biais.</p>
<p>On corrige les erreurs-types ainsi :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cov_c<span class="ot">&lt;-</span><span class="fu">vcovHC</span>(Fixed_temps,<span class="at">method=</span><span class="st">"arellano"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>robust_se_c<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov_c))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>et on obtient les résultats suivants :</p>
<table style="text-align:center">
<caption>
<strong>Modele poolé avec indicatrices temporels avec erreurs-types corrigées</strong>
</caption>
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
fhpolrigaug
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.145<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.031)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medage
</td>
<td>
-0.003
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.004)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
education
</td>
<td>
0.037<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.009)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
population
</td>
<td>
0.00000<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
nsave
</td>
<td>
-0.027
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.123)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
laborshare
</td>
<td>
0.296<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.116)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1960
</td>
<td>
-0.631<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.198)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1965
</td>
<td>
-0.681<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.200)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1970
</td>
<td>
-0.861<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.202)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1975
</td>
<td>
-0.904<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.204)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1980
</td>
<td>
-0.884<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.206)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1985
</td>
<td>
-0.826<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.205)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1990
</td>
<td>
-0.868<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.202)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
432
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.887
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.883
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.247 (df = 419)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
252.734<sup>***</sup> (df = 13; 419)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>On remarque que l’impact de la variable <code>laborshare</code> a perdu en significativité aprés la correction des erreurs type, il y avait donc une sur-interprétation de la significativité du coefficient. De plus l’impact des variables <code>education</code> et <code>population</code> perdent elles aussi en significativité.</p>
</section>
<section id="question-8" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-8">Question 8</h2>
<p>On conserve les effets temporels dans le modèle ainsi on estime le modèle à effets aléatoires suivant :</p>
<p><span class="math display">\[fhpolrigaug_{it} = \mu + \beta_1 lrgdpch_{it} + \beta_2 medage_{it} + \beta_3 education_{it} + \\ \beta_4 population_{it} + \beta_5 nsave_{it}
+ \beta_6 laborshare_{it} + \lambda_{t} + u_{it} \\ \text{où} \ u_{it}=\alpha_{i}+\varepsilon_{it}\]</span></p>
<p>avec le scalaire <span class="math inline">\(\mu\)</span> non-aléatoire rajouté pour que les effets aléatoires <span class="math inline">\(\alpha_i\)</span> soient normalisés de manière à obtenir une moyenne nulle.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>composed<span class="ot">&lt;-</span><span class="fu">plm</span>(fhpolrigaug<span class="sc">~</span>lrgdpch<span class="sc">+</span>medage<span class="sc">+</span>education<span class="sc">+</span>population<span class="sc">+</span>nsave<span class="sc">+</span>laborshare<span class="sc">+</span><span class="fu">factor</span>(year)<span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>Data,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">model=</span><span class="st">"random"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">effect =</span> <span class="st">"individual"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"code"</span>,<span class="st">"year"</span>))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>cov_f<span class="ot">&lt;-</span><span class="fu">vcovHC</span>(composed,<span class="at">method=</span><span class="st">"arellano"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>robust_se_f<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov_f))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table style="text-align:center">
<caption>
<strong>Modèle à effets aléatoires, avec erreur-type corrigé</strong>
</caption>
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
fhpolrigaug
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.132<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.047)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medage
</td>
<td>
-0.004
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.005)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
education
</td>
<td>
0.043<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.013)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
population
</td>
<td>
0.00000
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
nsave
</td>
<td>
-0.090
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.183)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
laborshare
</td>
<td>
0.212
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.138)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1960
</td>
<td>
-0.485<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.283)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1965
</td>
<td>
-0.533<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.288)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1970
</td>
<td>
-0.697<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.283)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1975
</td>
<td>
-0.742<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.289)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1980
</td>
<td>
-0.714<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.293)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1985
</td>
<td>
-0.666<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.292)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1990
</td>
<td>
-0.718<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.287)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
432
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.223
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.201
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
1,020.033<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
</section>
<section id="question-9" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-9">Question 9</h2>
<table style="text-align:center">
<caption>
<strong>Modele poolé à indicatrices temporelles (1) et modèle à erreurs composées (2) avec erreur type corrigé sur les deux modèles</strong>
</caption>
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
fhpolrigaug
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>OLS</em>
</td>
<td>
<em>panel</em>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em></em>
</td>
<td>
<em>linear</em>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.145<sup>***</sup>
</td>
<td>
0.132<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.031)
</td>
<td>
(0.047)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medage
</td>
<td>
-0.003
</td>
<td>
-0.004
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.004)
</td>
<td>
(0.005)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
education
</td>
<td>
0.037<sup>***</sup>
</td>
<td>
0.043<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.009)
</td>
<td>
(0.013)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
population
</td>
<td>
0.00000<sup>**</sup>
</td>
<td>
0.00000
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00000)
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
nsave
</td>
<td>
-0.027
</td>
<td>
-0.090
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.123)
</td>
<td>
(0.183)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
laborshare
</td>
<td>
0.296<sup>**</sup>
</td>
<td>
0.212
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.116)
</td>
<td>
(0.138)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1960
</td>
<td>
-0.631<sup>***</sup>
</td>
<td>
-0.485<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.198)
</td>
<td>
(0.283)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1965
</td>
<td>
-0.681<sup>***</sup>
</td>
<td>
-0.533<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.200)
</td>
<td>
(0.288)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1970
</td>
<td>
-0.861<sup>***</sup>
</td>
<td>
-0.697<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.202)
</td>
<td>
(0.283)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1975
</td>
<td>
-0.904<sup>***</sup>
</td>
<td>
-0.742<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.204)
</td>
<td>
(0.289)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1980
</td>
<td>
-0.884<sup>***</sup>
</td>
<td>
-0.714<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.206)
</td>
<td>
(0.293)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1985
</td>
<td>
-0.826<sup>***</sup>
</td>
<td>
-0.666<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.205)
</td>
<td>
(0.292)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1990
</td>
<td>
-0.868<sup>***</sup>
</td>
<td>
-0.718<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.202)
</td>
<td>
(0.287)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
432
</td>
<td>
432
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.887
</td>
<td>
0.223
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.883
</td>
<td>
0.201
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.247 (df = 419)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
252.734<sup>***</sup> (df = 13; 419)
</td>
<td>
1,020.033<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>L’objectif de la comparaison de ces deux modèles est d’observer les différences entre l’estimation par les MCO et l’estimation par les MCQG :</p>
<ul>
<li><p>Concernant l’impact de la variable <code>lrgdpch</code> , cette derniere est significative dans les deux modèles avec un coefficient supérieur dans le modèle poolé ;</p></li>
<li><p>Pour la variable <code>education</code> , le coefficient le plus fort se trouve dans le modèle a effets aléatoires, avec toujours une significativité élevée dans les deux modèles ;</p></li>
<li><p>On remarque que la variable <code>laborshare</code> est bien différente entre les deux modèles, pour le modèle a effets temporels, son coefficient est de <strong>0.296</strong> alors que dans le modele à erreurs composées le coefficient de la variable est de <strong>0.212</strong>, mais le plus gros changement concerne la significativité de la variable , en effet dans le modèle a erreurs composées l’impact de la variable n’est plus significatif, elle n’a donc aucun effet statistiquement significatif sur le degré de démocratie d’un pays ;</p></li>
<li><p>Il faut aussi noter que l’impact des effets fixes temporels sur le degré de démocratie est plus faible dans le modèle à effets aléatoires ;</p></li>
<li><p>Enfin, on notera que la qualité d’ajustement du modèle poolé est plus grande que la qualité d’ajustement du modèle à erreurs composées.</p></li>
</ul>
<p>De ces différrences entre le modèle poolé et le modèle à erreurs composées, nous pouvons déduire que la manière d’estimer les coefficients peut avoir un impact très puissant sur les résultats de notre étude.</p>
</section>
<section id="question-10" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-10">Question 10</h2>
<p>En partant du modèle ci-dessous :</p>
<p><span class="math display">\[fhpolrigaug_{it} = \beta_0 + \beta_1 lrgdpch_{it} + \beta_2 medage_{it} + \beta_3 education_{it} + \\ \beta_4 population_{it} + \beta_5 nsave_{it}
+ \beta_6 laborshare_{it} + \lambda_{t} + c_{i} + \varepsilon_{it}\]</span> Avec le modele théorique suivant, representant la transformation within :</p>
<p><span class="math display">\[y_{it} − \bar{y}_{i} = (x_{it} − \bar{x}_{i})'\beta + (\varepsilon_{it}-\bar\varepsilon_{i})\]</span> avec <span class="math inline">\(\beta\)</span> représentant le vecteur des coefficients et <span class="math inline">\((x_{it}-\bar{x_i})'\)</span> le vecteur des écarts à la moyenne de chaque coefficient.</p>
<p>On obtient le modele within suivant :</p>
<p><span class="math display">\[fhpolrigaug_{it} - \bar{fhpolrigaug_{i}} = \beta_1 lrgdpch_{it}' + \beta_2 medage_{it}' + \beta_3 education_{it}' + \\ \beta_4 population_{it}' + \beta_5 nsave_{it}'
+ \beta_6 laborshare_{it}' + \lambda'_{t} + \varepsilon'_{it}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>indiv<span class="ot">&lt;-</span><span class="fu">plm</span>(fhpolrigaug<span class="sc">~</span>lrgdpch<span class="sc">+</span>medage<span class="sc">+</span>education<span class="sc">+</span>population<span class="sc">+</span>nsave<span class="sc">+</span>laborshare<span class="sc">+</span><span class="fu">factor</span>(year)<span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>Data[<span class="fu">which</span>(<span class="sc">!</span><span class="fu">is.na</span>(Data<span class="sc">$</span>year)),],</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">model=</span><span class="st">"within"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">effect =</span><span class="st">"individual"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"code"</span>,<span class="st">"year"</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>cov_i<span class="ot">&lt;-</span><span class="fu">vcovHC</span>(indiv,<span class="at">method=</span><span class="st">"arellano"</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>robust_se_i<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov_i))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table style="text-align:center">
<caption>
<strong>Modele a effets fixes individuels (1) et modele a effet aleatoires (2), erreur type corrigé</strong>
</caption>
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
fhpolrigaug
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
lrgdpch
</td>
<td>
0.049
</td>
<td>
0.132<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.098)
</td>
<td>
(0.047)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
medage
</td>
<td>
-0.010
</td>
<td>
-0.004
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.010)
</td>
<td>
(0.005)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
education
</td>
<td>
0.039<sup>*</sup>
</td>
<td>
0.043<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.020)
</td>
<td>
(0.013)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
population
</td>
<td>
-0.00000<sup>*</sup>
</td>
<td>
0.00000
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00000)
</td>
<td>
(0.00000)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
nsave
</td>
<td>
0.050
</td>
<td>
-0.090
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.273)
</td>
<td>
(0.183)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
laborshare
</td>
<td>
0.024
</td>
<td>
0.212
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.151)
</td>
<td>
(0.138)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1960
</td>
<td>
0.133<sup>*</sup>
</td>
<td>
-0.485<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.080)
</td>
<td>
(0.283)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1965
</td>
<td>
0.102
</td>
<td>
-0.533<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.066)
</td>
<td>
(0.288)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1970
</td>
<td>
-0.042
</td>
<td>
-0.697<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.064)
</td>
<td>
(0.283)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1975
</td>
<td>
-0.070
</td>
<td>
-0.742<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.051)
</td>
<td>
(0.289)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1980
</td>
<td>
-0.016
</td>
<td>
-0.714<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.047)
</td>
<td>
(0.293)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1985
</td>
<td>
0.033
</td>
<td>
-0.666<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.034)
</td>
<td>
(0.292)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
factor(year)1990
</td>
<td>
</td>
<td>
-0.718<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.287)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
432
</td>
<td>
432
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.105
</td>
<td>
0.223
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
-0.158
</td>
<td>
0.201
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
3.253<sup>***</sup> (df = 12; 333)
</td>
<td>
1,020.033<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>
</tbody></table>
<p>Premièrement on remarque que l’impact de la variable représentant le logarithme du PIB par habitant est significatif uniquement dans le modèle a effet aléatoire, avec un coefficient de <strong>0.132</strong>, une hausse de 1% du PIB par tete entraine donc une hause de <strong>0.00132</strong> unité du niveau de démocratie se lon ce modèle.</p>
<p>Deuxièmement, l’impact de la variable <code>education</code> est significatif dans les deux modeles, cette derniere a une significativité, et un coefficient supérieure dans le modèle a effet aléatoire.</p>
<p>Troisièmement, en ce qui concerne l’impact de la variable <code>laborshare</code>, on remarque qu’elle perd sa significativité dans les deux modèles , ce qui indiquerait donc qu’une augmentation de la part du travail dans la valeur ajoutée n’influerait pas de maniere significative sur le niveau de démocratie.</p>
<p>Nous pouvons aussi porter notre regard sur la qualité d’ajustement des deux modèles, et l’on voit que le modele a effet aléatoire semble mieux ajusté que le modele a effets fixes individuelles avec des <span class="math inline">\(R^2\)</span> ajusté de respectivement 0.2007 et -0.1585.</p>
<p>D’ailleurs le <span class="math inline">\(R^{2}\)</span> ajusté négatif du modèle within sous-entendrait que nos variables explicatives n’apporteraient aucune information utile sur le niveau de démocratie.</p>
</section>
<section id="question-11" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-11">Question 11</h2>
<p>Avant de réfléchir par rapport aux données dont nous disposons, nous pouvons effectuer un test d’Haussman afin de nous aider a determiner quel modele retenir :</p>
<ul>
<li><p><span class="math inline">\(H_0 : E(u_i/X_i) = 0\)</span>, les effets individuels <span class="math inline">\(c_{i}\)</span> ne sont pas correles aux variables explicatives ;</p></li>
<li><p><span class="math inline">\(H_1 : E(u_i/X_i) ≠ 0\)</span>, les effets individuels <span class="math inline">\(c_{i}\)</span> sont correles aux variables explicatives</p></li>
</ul>
<p>ce test va tester la convergence de la différence entre l’estimateur à effets fixes et l’estimateur à effets aléatoires. Si la différence converge alors cela signifie que les deux estimateurs sont consistants.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Hauss<span class="ot">&lt;-</span><span class="fu">phtest</span>(indiv,composed,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>Data,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">method=</span><span class="st">"aux"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">vcov=</span>vcovHC)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">p.value</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">parameter</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">method</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">data.name</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">alternative</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2.04793232162683</td>
<td style="text-align: center;">0.999328743388981</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">Hausman Test</td>
<td style="text-align: center;">fhpolrigaug ~ lrgdpch + medage + education + population + nsave + ...</td>
<td style="text-align: center;">one model is inconsistent</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>La <span class="math inline">\(p_{value}\)</span> de <strong>0.999</strong>, indique que l’hypothèse nulle est retenue. Ainsi, il serait préférable de conserver le modèle à effets aléatoires.</p>
<p>Cependant, il est bon de retenir que nous avons un grand nombre d’observations manquantes, or, une mauvaise estimation des estimateurs dans les deux modèles tend à rendre le test peu robuste. De plus, des caractéristiques comme la culture ou l’histoire sont des facteurs propres à chaque pays et pourraient influer sur certaines de nos variables explicatives (comme la taille de la population ou encore le taux d’épargne) ce qui tend à contredire que les effets individuels sont aléatoires.</p>
<p>Par soucis de précaution, nous préférons choisir le modèle à effets fixes afin d’éviter d’utiliser le modèle aléatoire possiblement biaisé malgré les résultats du test d’Haussman.</p>
</section>
<section id="question-12" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-12">Question 12</h2>
<p>Afin de nous aider a determiner quel modèle choisir, nous pouvons nous appuyer sur différents test:</p>
<ul>
<li><p>Le test du lagrangien breush-pagan nous permet de choisir entre un modèle a effets aléatoires ou un modèle poolé.</p></li>
<li><p><span class="math inline">\(H_0: σ_{c} = 0 \ (Var(c ) = 0)\)</span> ; alors pas d’effets de panel, tous les individus ont le meme <span class="math inline">\(c_{i}\)</span> et donc il n’y a pas d’hétérogénéité individuelle dans nos données ;</p></li>
<li><p><span class="math inline">\(H_1: σ_c \neq 0\)</span> ; alors on a des effets de panel à prendre en compte, il y a présence d’hétérogénéité individuelle dans nos données.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>bp_test <span class="ot">&lt;-</span> <span class="fu">bptest</span>(Fixed_temps,<span class="at">data =</span> Data)  </span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">parameter</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">method</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">p.value</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">data.name</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">42.0022476839476</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">studentized Breusch-Pagan test</td>
<td style="text-align: center;">3.32763070602702e-05</td>
<td style="text-align: center;">Fixed_temps</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Au vue de la <span class="math inline">\(p_{value}\)</span> du test on rejette l’hypothèse de nullité, il y a présence d’effet panel, il faudrait donc retenir le modèle a effets aléatoires.</p>
<p>Le test de fisher permet quand a lui de nous aider a choisir entre un modèle dit poolé ou un modèle a effets fixes.</p>
<ul>
<li><p><span class="math inline">\(H_0:\)</span> Tous les <span class="math inline">\(c_i = 0\)</span>, alors pas d’effets de panel, il n’y a pas d’hétérogénéité individuelle dans nos données ;</p></li>
<li><p><span class="math inline">\(H_1 :\)</span> Au moins un <span class="math inline">\(c_i \neq 0\)</span> alors on a des effets de panel à prendre en compte, il y a de l’hétérogénéité individuelle dans nos données.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pF_test <span class="ot">&lt;-</span> <span class="fu">pFtest</span>(indiv,Fixed_temps)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important; color: black !important; background-color: grey !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important; color: black !important; background-color: grey !important;">Résultats du test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; color: black !important; background-color: grey !important;">df1</td>
<td style="text-align: center;">333</td>
</tr>
<tr class="even">
<td style="text-align: center; color: black !important; background-color: grey !important;">statistic</td>
<td style="text-align: center;">4.44143282471324</td>
</tr>
<tr class="odd">
<td style="text-align: center; color: black !important; background-color: grey !important;">p.value</td>
<td style="text-align: center;">5.60742341999254e-23</td>
</tr>
<tr class="even">
<td style="text-align: center; color: black !important; background-color: grey !important;">df2</td>
<td style="text-align: center;">86</td>
</tr>
<tr class="odd">
<td style="text-align: center; color: black !important; background-color: grey !important;">method</td>
<td style="text-align: center;">F test for individual effects</td>
</tr>
<tr class="even">
<td style="text-align: center; color: black !important; background-color: grey !important;">formula</td>
<td style="text-align: center;">fhpolrigaug ~ lrgdpch + medage + education + population + nsave + ...</td>
</tr>
<tr class="odd">
<td style="text-align: center; color: black !important; background-color: grey !important;">alternative</td>
<td style="text-align: center;">significant effects</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Au regard de la <span class="math inline">\(p_{value}\)</span> extrêmement faible, on rejette <span class="math inline">\(H_0\)</span> et on constate donc la presence d’au moins un effet individuel différent de <span class="math inline">\(0\)</span> et ainsi la présence d’hétérogénéité individuelle dans nos données.</p>
<p>En ne considérant que les résultats de chaque test, on constate que des effets individuels sont à prendre en compte dans l’estimation des modèles et le test d’Haussman tend à recommander le modèle à effets aléatoires. Cependant, notre réponse à la précédente question illustre notre préférence du modèle à effets fixes que nous jugeons plus approprié à nos données.</p>
</section>
<section id="question-13" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-13">Question 13</h2>
<p>Ainsi, la conclusion la plus expéditive serait d’admettre que le PIB par habitant n’aurait pas d’impact significatif sur le niveau de démocratie d’un pays. En effet, la prise en compte d’un grand nombre de facteurs dont des variables que l’on pourrait estimer corrélée avec le PIB par habitant comme le taux d’épargne, la taille de la population,… ainsi que la prise en compte de la dimension temporelle de nos données et de la très probable présence d’hétérogénité individuelle conduirait à minimiser un impact que l’on pouvait imaginer très fort avant l’étude.</p>
<p>Cependant, il faut rester prudent et prendre ces résultats avec des pincettes au vu de la présence d’un très grand nombre de données manquantes, en effet nous disposions de <strong>2321</strong> observations mais le modèle n’est estimé que sur une base de <strong>432</strong> observations, il y a donc probablement une différence entre nos résultats et la réalité.</p>
</section>
</section>
<section id="exercice-2" class="level1 unnumbered">
<h1 class="unnumbered">Exercice 2</h1>
<section id="question-1-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-1-1">Question 1</h2>
<p>On simule <span class="math inline">\(Y_t = 0.8Y_{t-1} + 0.1Y_{t-2} + 0.3\varepsilon_{t-1} + \varepsilon_t\)</span> de longueur <span class="math inline">\(T = 200\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>simulation<span class="ot">&lt;-</span><span class="fu">arima.sim</span>(<span class="fu">list</span>(<span class="at">ar=</span><span class="fu">c</span>(<span class="fl">0.8</span>,<span class="fl">0.1</span>),<span class="at">ma=</span><span class="fu">c</span>(<span class="fl">0.3</span>)),<span class="at">n=</span><span class="dv">200</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Voici une représentation graphique de notre simulation :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-2-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-2-1">Question 2</h2>
<p>Voici la forme de la fonction d’autocorrélation simple de notre simulation :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On remarque que les 11 premiers pics de la fonction d’autocorrélation simple sont significatifs, il y aurait donc une corrélation significative entre <span class="math inline">\(Y\)</span> et les 11 dernières valeurs de <span class="math inline">\(Y\)</span>, cette même fonction a une décroissance plutôt exponentielle, cette fonction nous laisse supposer que nous faisons face à un modèle ARMA ou à un modèle AR.</p>
<p>Voici la forme de la fonction d’autocorrélation partielle de notre simulation :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Seul les deux premiers pics de la fonction d’autocorrélation partielle sont significatifs, de plus celle-ci décroît de manière sinusoïdale, ces informations pourraient laisser penser à un AR d’ordre 2.</p>
</section>
<section id="question-3-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-3-1">Question 3</h2>
<p>La fonction d’autocorrélation partielle a une décroissance sinusoïdale à partir du <span class="math inline">\(1^{er}\)</span> retard. Dans un soucis de parcimonie, nous préférons ajuster la simulation avec un modèle <strong>ARMA(2,1)</strong> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>arma2_1 <span class="ot">&lt;-</span> <span class="fu">arima</span>(simulation,<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nous avons les coefficients de ce modèle dans ce tableau :</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">I</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Coefficients</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Std_Error</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Résultats</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ar1</td>
<td style="text-align: center;">0.3035</td>
<td style="text-align: center;">0.2045</td>
<td style="text-align: center; border-left: 1px solid;">AIC = 558.66</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ar2</td>
<td style="text-align: center;">0.4726</td>
<td style="text-align: center;">0.1931</td>
<td style="text-align: center; border-left: 1px solid;">sigma² = 0.9021</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ma1</td>
<td style="text-align: center;">0.7661</td>
<td style="text-align: center;">0.1670</td>
<td style="text-align: center; border-left: 1px solid;">Log_likelihood = -274.3306</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">intercept</td>
<td style="text-align: center;">-0.1066</td>
<td style="text-align: center;">0.5156</td>
<td style="text-align: center; border-left: 1px solid;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Nous avons donc un ARMA(2,1) de la forme :</p>
<p><span class="math inline">\(Y_t = 0.3035Y_{t-1} + 0.4726Y_{t-2} + 0.7661\varepsilon_{t-1} - 0.1068\)</span></p>
<p>où tous les coefficicents sont significativement différent de 0 à l’exception de la constante. On notera aussi une variance <span class="math inline">\(\sigma² = 0.9021\)</span></p>
<p>Etudions à présent les résidus de ce modèle :</p>
<p>Pour commencer, voici une représentation graphique :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La forme des fonctions d’autocorrélation simple et partielle sont les suivantes :</p>
<center>
<strong>Les fonctions d’autocorrélations de l’ARMA(2,1)</strong>
</center>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Le modèle ARMA(2,1) semble adapté à notre simulation, en effet le premier lag de ce modèle ne semble pas corrélé aux autres lags.</p>
</section>
<section id="question-4-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-4-1">Question 4</h2>
<p>On ajuste la simulation avec un modèle <strong>AR(3)</strong> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>AR3 <span class="ot">&lt;-</span> <span class="fu">arima</span>(simulation,<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nous avons les coefficients de ce modèle dans ce tableau :</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">I</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Coefficients</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Std_Error</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Résultats</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ar1</td>
<td style="text-align: center;">1.0610</td>
<td style="text-align: center;">0.0702</td>
<td style="text-align: center; border-left: 1px solid;">AIC = 562.03</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ar2</td>
<td style="text-align: center;">-0.2856</td>
<td style="text-align: center;">0.1017</td>
<td style="text-align: center; border-left: 1px solid;">sigma² = 0.9179</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ar3</td>
<td style="text-align: center;">0.0966</td>
<td style="text-align: center;">0.0721</td>
<td style="text-align: center; border-left: 1px solid;">Log_likelihood = -276.0169</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">intercept</td>
<td style="text-align: center;">-0.1045</td>
<td style="text-align: center;">0.5162</td>
<td style="text-align: center; border-left: 1px solid;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Nous avons donc un AR(3) de la forme :</p>
<p><span class="math inline">\(Y_t = 1.0610Y_{t-1} - 0.2856Y_{t-2} + 0.0966Y_{t-3} - 0.1045\)</span></p>
<p>où tous les coefficicents sont significativement différent de 0 à l’exception de la constante. On notera aussi une variance <span class="math inline">\(\sigma² = 0.9179\)</span>.</p>
<p>Etudions à présent les résidus de ce modèle :</p>
<p>Pour commencer, voici une représentation graphique :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La forme des fonctions d’autocorrélation simple et partielle sont les suivantes :</p>
<center>
<strong>Les fonctions d’autocorrélations de l’AR(3)</strong>
</center>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La forme des fonctions d’autocorrélations du modèle <strong>AR(3)</strong> semble démontrer par l’absence de corrélations significatives que cette modélisation semble plutôt adapté à la simulation, on notera tout de même la présence d’un pic significatif pour la fonction d’autocorrélation partielle et de plusieurs pics presque significatifs pour les deux fonctions.</p>
<p>On ajuste la simulation avec un modèle <strong>MA(3)</strong> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>MA3 <span class="ot">&lt;-</span> <span class="fu">arima</span>(simulation,<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">3</span>))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nous avons les coefficients de ce modèle dans ce tableau :</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">I</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Coefficients</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Std_Error</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Résultats</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ma1</td>
<td style="text-align: center;">1.1144</td>
<td style="text-align: center;">0.0696</td>
<td style="text-align: center; border-left: 1px solid;">AIC = 589.17</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ma2</td>
<td style="text-align: center;">0.7491</td>
<td style="text-align: center;">0.0797</td>
<td style="text-align: center; border-left: 1px solid;">sigma² = 1.0518</td>
</tr>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ma3</td>
<td style="text-align: center;">0.3983</td>
<td style="text-align: center;">0.0564</td>
<td style="text-align: center; border-left: 1px solid;">Log_likelihood = -289.5867</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">intercept</td>
<td style="text-align: center;">-0.2072</td>
<td style="text-align: center;">0.2352</td>
<td style="text-align: center; border-left: 1px solid;"></td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Nous avons donc un MA(3) de la forme :</p>
<p><span class="math inline">\(Y_t = 1.1144\varepsilon_{t-1} + 0.7491\varepsilon_{t-2} + 0.3983Y_{t-3} - 0.2072\)</span></p>
<p>où tous les coefficicents sont significativement différent de 0 à l’exception de la constante. On notera aussi une variance <span class="math inline">\(\sigma² = 1.0518\)</span></p>
<p>Etudions à présent les résidus de ce modèle :</p>
<p>Pour commencer, voici une représentation graphique :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La forme des fonctions d’autocorrélation simple et partielle sont les suivantes :</p>
<center>
<strong>Les fonctions d’autocorrélations du MA(3)</strong>
</center>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La forme des fonctions d’autocorrélations du modèle <strong>MA(3)</strong> semble démontrer par la présence de plusieurs corrélations significatives que cette modélisation ne semble pas adapté à la simulation.</p>
</section>
<section id="question-5-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-5-1">Question 5</h2>
<p>Pour determiner si nous sommes en présence de Bruit Blanc nous pouvons effectuer le test de Box-Pierce</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>B_test <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">Box.test</span>(arma2_1<span class="sc">$</span>residuals),</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>               <span class="fu">Box.test</span>(AR3<span class="sc">$</span>residuals),</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>               <span class="fu">Box.test</span>(MA3<span class="sc">$</span>residuals))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">stat.X-squared</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">Modèle ARMA(2,1)</td>
<td style="text-align: center;">0.0732017</td>
<td style="text-align: center;">0.7867309</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">Modèle AR(3)</td>
<td style="text-align: center;">0.0179746</td>
<td style="text-align: center;">0.8933477</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">Modèle MA(3)</td>
<td style="text-align: center;">1.6425642</td>
<td style="text-align: center;">0.1999740</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>On remarque que les trois tests aboutissent sur des p-values élevées, indiquant donc que nous conservons l’hypothése de blancheur des résidus , et nous sommes donc en présence d’un <strong>bruit blanc</strong> dans les trois modèles.</p>
<p>On peut aussi effectuer un test de shapiro :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Shap_test <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">shapiro.test</span>(arma2_1<span class="sc">$</span>residuals),</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>               <span class="fu">shapiro.test</span>(AR3<span class="sc">$</span>residuals),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>               <span class="fu">shapiro.test</span>(MA3<span class="sc">$</span>residuals))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">stat.W</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">Modèle ARMA(2,1)</td>
<td style="text-align: center;">0.9867</td>
<td style="text-align: center;">0.0573</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">Modèle AR(3)</td>
<td style="text-align: center;">0.9836</td>
<td style="text-align: center;">0.0196</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">Modèle MA(3)</td>
<td style="text-align: center;">0.9938</td>
<td style="text-align: center;">0.5697</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>En prenant un seuil de significativité de 5%, on remarque que seul les résidus du modèle AR(3) sont un bruit gaussien.</p>
<p>Il nous reste à vérifier la stationnarité des modèles, pour cela nous allons effectuer le test de Dickey-Fuller dont les hypothèses sont les suivantes :</p>
<ul>
<li><span class="math inline">\(H_0\)</span> : Le processus n’est pas stationnaire</li>
<li><span class="math inline">\(H_1\)</span> : Le processus est stationnaire</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ur.df</span>(arma2_1<span class="sc">$</span>residuals, <span class="at">lags =</span> <span class="dv">20</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ur.df</span>(AR3<span class="sc">$</span>residuals, <span class="at">lags =</span> <span class="dv">20</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ur.df</span>(MA3<span class="sc">$</span>residuals, <span class="at">lags =</span> <span class="dv">20</span>)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Test de Dickey-Fuller</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">1%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">5%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">10%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">Test Stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important;">ARMA(2,1)</td>
<td style="text-align: center;">-2.58</td>
<td style="text-align: center;">-1.95</td>
<td style="text-align: center;">-1.62</td>
<td style="text-align: center;">-3.270578</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important;">AR(3)</td>
<td style="text-align: center;">-2.58</td>
<td style="text-align: center;">-1.95</td>
<td style="text-align: center;">-1.62</td>
<td style="text-align: center;">-3.250415</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; color: black !important; background-color: grey !important;">MA(3)</td>
<td style="text-align: center;">-2.58</td>
<td style="text-align: center;">-1.95</td>
<td style="text-align: center;">-1.62</td>
<td style="text-align: center;">-2.883262</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Les trois tests de dickey-Fuller ont des statistiques de test inférieur aux différents seuils, ce qui conduit à rejeter l’hypothèse de non-stationnarité, donc les trois processus sont stationnaires.</p>
</section>
<section id="question-6-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-6-1">Question 6</h2>
<p>L’autre critère que l’on pourrait utiliser pour choisir entre les 3 modèles est le critère <strong>AIC</strong> (Criterium d’Information d’Akaike) qui cherche à trouver un équilibre entre l’ajustement du modèle aux données observées et la parcimonie du modèle. Il faut donc noter que ce critère pénalise les modèles utilisant un plus grand nombre de paramètres car sa minimisation conduit à préfèrer des modèles moins complexes qui expliqueraient aussi bien les données mais avec moins de paramètres. L’objectif fixé lorsque l’on utilise le critère AIC est la minimisation du score AIC donc les modèles avec les plus petits scores seront les plus performant avec ce point de vue.</p>
<p><span class="math inline">\(AIC=−2×log(L)+2×k\)</span></p>
<p>où :</p>
<ul>
<li><p><span class="math inline">\(L\)</span> est la fonction de maximum de vraisemblance du modèle (log-vraisemblance maximisée),</p></li>
<li><p><span class="math inline">\(k\)</span> est le nombre de paramètres estimés dans le modèle.</p></li>
</ul>
<p>On remarque donc la pénalité subit par les modèles contenant plus de paramètres. La fonction du log-vraisemblance maximisée permettra de mesurer la qualité d’ajustement du modèle. On identifie donc un arbitrage entre qualité d’ajustement du modèle et parcimonie.</p>
<p>Pour conclure sur l’utilisation de ce critère, un modèle avec un AIC plus bas indique que le modèle a une meilleure capacité à expliquer les données tout en utilisant moins de paramètres. Il faut tout de même rester prudent avec son utilisation car il ne fournit pas d’indication absolue de la qualité d’ajustement du modèle.</p>
<p>Notre connaissance de la série <span class="math inline">\(Y_{t} = 0.8Y_{t-1} + 0.1Y_{t-2} + 0.3\varepsilon_{t-1} + \varepsilon_{t}\)</span> nous inciterait à choisir un modèle ARMA(2,1) …</p>
<p>De plus c’est le modèle ARMA (2,1) qui dispose du score <strong>AIC</strong> le plus faible, <strong>558.66</strong>, parmi les 3 modèles que l’on a testé, les résidus étant des bruits blancs pour les 3 modèles, on peut considérer que le modèle <strong>ARMA(2,1)</strong> est adapté pour représenter la série.</p>
</section>
<section id="question-7-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-7-1">Question 7</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>auto <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(simulation) </span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">I</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Coefficients</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Std_Error</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; font-style: italic; color: black !important; background-color: grey !important;">Résultats</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ar1</td>
<td style="text-align: center;">0.8229</td>
<td style="text-align: center;">0.0469</td>
<td style="text-align: center; border-left: 1px solid;">AIC = 558.18</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important; border-left: 1px solid; border-right: 1px solid;">ma1</td>
<td style="text-align: center;">0.2642</td>
<td style="text-align: center;">0.0883</td>
<td style="text-align: center; border-left: 1px solid;">sigma² = 0.9278</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>auto.arima nous suggère d’utiliser un modèle <strong>ARMA(1,1)</strong>, d’ailleurs ce modèle fournit un AIC plus faible que le modèle <strong>ARMA(2,1)</strong>.</p>
<p>Ce modèle prend la forme suivante :</p>
<p><span class="math inline">\(Y_t = 0.8229Y_{t-1} + 0.2642\varepsilon_{t-1} + \varepsilon_t\)</span></p>
<p>où tous les coefficicents sont significativement différent de 0 à l’exception de la constante. On notera aussi une variance <span class="math inline">\(\sigma² =\)</span> 0.9278.</p>
<p>Assurons-nous que ce modèle <strong>ARMA(1,1)</strong> soit bien adapté à la situation, nous allons étudier ses résidus :</p>
<p>Tout d’abord, voici une représentation graphique de ses résidus :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<center>
<strong>Les fonctions d’autocorrélations de l’ARMA(1,1)</strong>
</center>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="meth_econo_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La forme des fonctions d’autocorrélations du modèle <strong>ARMA(1,1)</strong> semble démontrer par l’absence de corrélations significatives que cette modélisation semble plutôt adapté à la simulation, on notera tout de même la présence d’un pic significatif pour la fonction d’autocorrélation partielle et de plusieurs pics presque significatifs pour les deux fonctions.</p>
<p>Il nous reste à étudier la blancheur des résidus :</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Pierce test

data:  auto$residuals
X-squared = 0.040059, df = 1, p-value = 0.8414</code></pre>
</div>
</div>
<p>La <span class="math inline">\(p_{value}\)</span> de 0.8414 est en faveur de la blancheur des résidus, nous sommes donc en présence d’un bruit blanc.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  auto$residuals
W = 0.98259, p-value = 0.01404</code></pre>
</div>
</div>
<p>La <span class="math inline">\(p_{value}\)</span> de 0.014 démontre la présence d’un bruit gaussien si l’on se réfère à un seuil de significativité de 5%.</p>
<p>Il nous reste à vérifier la stationnarité du modèle, pour cela nous allons effectuer le test de Dickey-Fuller :</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Test de Dickey-Fuller</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">Modèle</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">1%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">5%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">10%</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">Test Stat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; font-weight: bold; color: black !important; background-color: grey !important;">ARMA(1,1)</td>
<td style="text-align: center;">-2.58</td>
<td style="text-align: center;">-1.95</td>
<td style="text-align: center;">-1.62</td>
<td style="text-align: center;">-3.174052</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Le test conduit à rejeter l’hypothèse de non-stationnarité, donc le processus ARMA(1,1) est stationnaire.</p>
</section>
<section id="question-8-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="question-8-1">Question 8</h2>
<p>Ce résultat est assez perturbant car lors de la première question, nous avions simulé un modèle qui semblait être un <strong>ARMA(2,1)</strong> mais cette situation s’explique par le fait que le critère <strong>AIC</strong> favorise la parcimonie, et donc des modèles contenant moins de paramètres, tout en maintenant de la cohérence avec les données. Sachant cela, on identifie que le fait qu’un <strong>ARMA(1,1)</strong> contienne moins de paramètre que <strong>l’ARMA(2,1)</strong> pourrait entrainer un score <strong>AIC</strong> plus faible. La commande auto.arima étant programmé pour sélectionner le modèle contenant le score AIC le plus faible parmi ceux qu’elle teste, la commande finira par sélectionner un modèle <strong>ARMA(1,1)</strong> contenant moins de paramètres mais minimisant le score <strong>AIC</strong>.</p>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Retour au sommet</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/hugocoche\.github\.io\/website\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2024, Hugo COCHEREAU</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../licence.html" target="_blank">
<p>Licence : CC BY-NC-SA</p>
</a>
  </li>  
</ul>
    <div class="cookie-consent-footer"><a href="#" id="open_preferences_center">🍪 Paramètres des cookies</a></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://quarto.org/" target="_blank">
<p>🛠️ Réalisé avec <strong>Quarto</strong></p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>